version: 0.0
os: linux
files:
  - source: foori/dist/
    destination: /home/ec2-user/Foori/foori/dist
    overwrite: yes
  - source: foori/nginx.conf
    destination: /etc/nginx/conf.d/default.conf
    overwrite: yes

hooks:
  BeforeInstall:
    - location: foori/scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: foori/scripts/start_application.sh
      timeout: 300
      runas: root
