version: 0.0
os: linux
files:
  - source: /foori
    destination: /home/ec2-user/Foori/foori
permissions:
  - object: /home/ec2-user/Foori/foori/dist
    owner: ec2-user
    group: ec2-user
    mode: 755
  - object: /etc/nginx/conf.d/
    owner: root
    group: root
    mode: 644
hooks:
  BeforeInstall:
    - location: foori/scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: foori/scripts/start_application.sh
      timeout: 300
      runas: ec2-user
