version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    image: foori-frontend
    container_name: foori-frontend
    ports:
      - '80:80'
    restart: unless-stopped # 변경
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
