version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_KAKAO_MAP_KEY=${VITE_KAKAO_MAP_KEY}
    image: foori-frontend
    container_name: foori-frontend
    ports:
      - '80:80'
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
