version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    args:
      - VITE_KAKAO_MAP_KEY=${VITE_KAKAO_MAP_KEY}
      - VITE_REDIRECT_URL=${VITE_REDIRECT_URL}
      - VITE_SOCIAL_LOGIN_URL=${VITE_SOCIAL_LOGIN_URL}
      - VITE_SOCIAL_CONNECT_URL=${VITE_SOCIAL_CONNECT_URL}
      - VITE_BACK_URL=${VITE_BACK_URL}
    image: foori-frontend
    container_name: foori-frontend
    ports:
      - '80:80'
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
