version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - foori-frontend:latest
    image: foori-frontend:latest
    container_name: foori-frontend
    ports:
      - '80:80'
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
