name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Create CodeDeploy Deployment
        env:
          VITE_KAKAO_MAP_KEY: ${{ secrets.VITE_KAKAO_MAP_KEY }}
          VITE_TOSS_CLIENT_KEY: ${{ secrets.VITE_TOSS_CLIENT_KEY }}
          VITE_BACK_URL: ${{ secrets.VITE_BACK_URL }}
          VITE_REDIRECT_URL: ${{ secrets.VITE_REDIRECT_URL }}
          VITE_SOCIAL_LOGIN_URL: ${{ secrets.VITE_SOCIAL_LOGIN_URL }}
          VITE_SOCIAL_CONNECT_URL: ${{ secrets.VITE_SOCIAL_CONNECT_URL }}
        run: |
          aws deploy create-deployment \
            --application-name foori \
            --deployment-group-name foori-group \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
