name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/Foori/foori
            git pull origin main

            # 이전 이미지 ID 저장
            OLD_IMAGE_ID=$(docker images -q foori-frontend)

            # BuildKit 활성화하고 빌드
            DOCKER_BUILDKIT=1 docker-compose build --parallel

            # 컨테이너 재시작
            docker-compose up -d

            # 이전 이미지 정리
            if [ ! -z "$OLD_IMAGE_ID" ]; then
              docker rmi $OLD_IMAGE_ID
            fi

            # 불필요한 빌드 캐시만 정리
            docker builder prune -f --filter until=24h
