name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and build
        run: |
          cd foori
          npm install
          npm run build
        env:
          VITE_KAKAO_MAP_KEY: ${{ secrets.VITE_KAKAO_MAP_KEY }}
          VITE_TOSS_CLIENT_KEY: ${{ secrets.VITE_TOSS_CLIENT_KEY }}
          VITE_BACK_URL: ${{ secrets.VITE_BACK_URL }}
          VITE_REDIRECT_URL: ${{ secrets.VITE_REDIRECT_URL }}
          VITE_SOCIAL_LOGIN_URL: ${{ secrets.VITE_SOCIAL_LOGIN_URL }}
          VITE_SOCIAL_CONNECT_URL: ${{ secrets.VITE_SOCIAL_CONNECT_URL }}

      # ZIP 파일 생성할 때 전체 경로 포함
      - name: Make zip file
        run: |
          zip -r ./$GITHUB_SHA.zip ./foori/dist ./foori/nginx.conf ./foori/scripts
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Upload to S3
        run: |
          aws s3 cp ./$GITHUB_SHA.zip s3://foori-deploy/$GITHUB_SHA.zip

      - name: Deploy to EC2
        run: |
          aws deploy create-deployment \
            --application-name foori \
            --deployment-group-name foori-group \
            --s3-location bucket=foori-deploy,key=$GITHUB_SHA.zip,bundleType=zip
