name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/Foori/foori
            git pull origin main

            # Docker 시스템 완전 정리
            docker system prune -af --volumes

            # BuildKit 활성화하고 빌드
            DOCKER_BUILDKIT=1 docker-compose build --parallel

            # 컨테이너 재시작
            docker-compose up -d
