name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 소스코드 체크아웃
        uses: actions/checkout@v4

      - name: EC2 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/Foori/foori
            cat << EOF > .env
            VITE_KAKAO_MAP_KEY=${VITE_KAKAO_MAP_KEY}
            VITE_TOSS_CLIENT_KEY=${VITE_TOSS_CLIENT_KEY}
            VITE_BACK_URL=${VITE_BACK_URL}
            VITE_REDIRECT_URL=${VITE_REDIRECT_URL}
            VITE_SOCIAL_LOGIN_URL=${VITE_SOCIAL_LOGIN_URL}
            VITE_SOCIAL_CONNECT_URL=${VITE_SOCIAL_CONNECT_URL}
            EOF
            git pull origin main
            docker-compose down
            docker-compose up -d --build
