name: Deploy to EC2

on:
  push:
    branches: [main] # main 브랜치에 push할 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # EC2 퍼블릭 IP
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }} # EC2 접속 키
          script: |
            cd ~/Foori/foori
            git pull origin main
            docker-compose down
            docker system prune -f
            docker-compose up -d --build
