name: Deploy to EC2

on:
  push:
    branches: [main]
    paths:
      - 'foori/**' # foori 디렉토리 변경시에만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/Foori/foori
            git pull origin main

            # 이전 이미지/컨테이너 정리
            docker-compose down --remove-orphans
            docker system prune -af

            # 캐시 사용하여 빌드
            docker-compose build --no-cache frontend
            docker-compose up -d
