name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃
        uses: actions/checkout@v4

      - name: EC2에 SSH 접속 및 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. 소스코드 최신화
            echo "🔄 소스코드 업데이트 중..."
            cd ~/Foori/foori
            git pull origin main

            # 2. Docker 빌드 준비
            echo "🏗️ Docker 빌드 준비 중..."
            export DOCKER_BUILDKIT=1
            export COMPOSE_DOCKER_CLI_BUILD=1
            OLD_IMAGE_ID=$(docker images -q foori-frontend)

            # 3. 새 이미지 빌드
            echo "🚀 새 이미지 빌드 중..."
            docker-compose build \
              --build-arg BUILDKIT_INLINE_CACHE=1 \
              --parallel

            # 4. 컨테이너 교체
            echo "🔄 컨테이너 교체 중..."
            docker-compose down
            docker-compose up -d

            # 5. 정리
            echo "🧹 불필요한 리소스 정리 중..."
            if [ ! -z "$OLD_IMAGE_ID" ]; then
              docker rmi $OLD_IMAGE_ID
            fi

            # 6. 배포 확인
            echo "✅ 배포 완료! 컨테이너 상태:"
            docker ps | grep foori-frontend
